medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: medical_user
      password: medical_pass
      dbname: medical_warehouse
      schema: staging
      threads: 1
    ci:
      type: postgres
      host: localhost
      port: 5432
      user: test_user
      password: test_pass
      dbname: test_db
      schema: staging
      threads: 4